plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Machina Ratiocinatrix
description: Machina Ratiocinatrix is a term used by Norbert Wiener in the introduction to his book Cybernetics, or Control and Communication in the Animal and the Machine
